### ISSUE TITLE
How to extend the stableswap implementation to 3-pool?

### ISSUE THREAD

**Issue by diwu1989** [terminal-fi/swappa#29]
I think we need to have a 3-pool or arbitrary N-pool version of stableswap implementation.
Curve has many pools that are 3-stables

**Comment by zviadm** [comment]
It depends how complex you want the routing to be. If we assume that any pool is only used once in a swap, then all pairs from a pool can be added independently with the same PairKey and it should all just work. 

If you want more complex routing (like swapping token for 2 other tokens and then having separate routes and all that), that will require much bigger changes, and probably swappa's current framework wont be able to handle that. That is something that would have to happen ins SwappV2 and should probably be a complete rewrite :)

**Comment by diwu1989** [comment]
I got the 3-pool and 4-pool stable swap to work, it only uses each pool once in a arb swap, but that's good enough to capture all the profits for now.

Refactored the current 2-pool stableswap functions to be the N-pool version.
