### ISSUE TITLE
Proposal: add intermediate stage output amount checks

### ISSUE THREAD

**Issue by diwu1989** [terminal-fi/swappa#3]
This is a proposal that will likely require updating the core router contract.

The idea is that right now, we have a safety output amount check at the very end of the sequence of swaps.
This is fine if the gas is low, but during arbs, the current gas bidding goes as high as 600+ gwei, so it's quite dangerous.

What do you think about the idea of:
1. encoding optional per swap output limit in the current extra data field
2. after each round of swap, if there's a output limit defined, check that
3. revert anytime an intermediate limit is not met

Would like to get some feedback on this idea before implementing it.

**Comment by diwu1989** [comment]
One idea is the change the interface of `swap()` to return the output amount, and then in the router, after each swap, check the actual output amount against the limit for that stage of the path.
```
interface ISwappaPairV1 {
	function swap(
		address input,
		address output,
		address to,
		bytes calldata data
	) external;
```

**Comment by zviadm** [comment]
Tbh, this library wasn't really meant to be used as much for arbing, just mostly for regular trading. 
I think this change can complicate things unnecessarily for libraries primary use case. Also I think it will increase gas consumption in regular use-case which generally expects that TX will succeed and gas price will be pretty small.

**Comment by diwu1989** [comment]
For the normal use-cases where humans are sending 0.5gwei normal transactions, the cost of the extra call data and return data and output checks should still be very negligible.

When the optional per-swap intermediate limits are not defined in the input, I think there are ways to short circuit the logic and not have any noticeable extra gas consumption.

I'll code something up and see how it performs. I feel like we can have the library work both for humans and for arbs.

By transaction volume, almost all of the current transactions into swappa are from arb:
https://explorer.celo.org/address/0x32045d4a35Cfb581E067668F0D00feebf77690E0/transactions

**Comment by diwu1989** [comment]
There should be negligible extra gas consumption if the input limits are not passed in via `extraData`:
https://github.com/terminal-fi/swappa/pull/4

Implemented it as an inputAmount check because we already pay the cost per swap to read the input token amount, extra cost is just a conditional check, and another conditional with mload to read the optional limit
