### ISSUE TITLE
Upgrade celo dependencies 

### ISSUE THREAD

**Issue by aaronmgdr** [terminal-fi/swappa#58]
Hi I notice that swappa is using a version of contractkit that Might build transactions of a type that will not work on cel2. If you are using eip1559 style transactions you should be fine. but to be safe best to upgrade to 8.0

https://github.com/terminal-fi/swappa/blob/bb390b90525b98f707176d5adcb34ebc27dff391/package.json#L8-L9

**Comment by zviadm** [comment]
sdks have been upgraded
