### ISSUE TITLE
Proposal: integrate Symmetric finance DEX

### ISSUE THREAD

**Issue by diwu1989** [terminal-fi/swappa#6]
Their exchange interface:
https://github.com/centfinance/Symmetric.Core/blob/develop/contracts/proxies/ExchangeProxy.sol#L20-L28

There's about anywhere between 100 to 300 celo daily of uncontested arb profit on Symmetric right now.
Would like to implement Symmetric Pair and add it as a DEX liquidity source.

**Comment by zviadm** [comment]
Integrating Symmetric would be fantastic. I have just been too lazy to parse out all their contract intricacies to implement it. 
One hint: To add multi-token pools (i.e. pools with 3 or more tokens), you need to create every single possible Pair, but use same 'PairKey' for all of them. This is the way the system is designed to support multi-token pools.

Example: Pool has tokens: A, B, C, you will create Pairs of A/B, A/C, B/C but all of them with the same PairKey which is generally address of the pool itself.

**Comment by diwu1989** [comment]
I think will start with a simple version that only deal with dual-token pool, just to get the arbs started.

The multi-token pool is more complicated, that same pool can be re-used in the swap path entering and exiting as different pairs though right?

**Comment by diwu1989** [comment]
okay i think i know what you mean, will take a stab at it

**Comment by diwu1989** [comment]
They have decent offline javascript calculations already:
https://github.com/centfinance/Symmetric.Core/blob/develop/lib/calc_comparisons.js

**Comment by diwu1989** [comment]
They dont have on-chain registry yet, their UI uses a static json i think:
https://storageapi.fleek.co/switch1983-team-bucket/cent-exchange-celo/pools

**Comment by diwu1989** [comment]
GraphQL to get all their pools:
```
{
  pools {
    id
    tokens {
      id
      name
      symbol
      balance
      denormWeight
    }
    swapFee
    controller
    publicSwap
    finalized
  }
}
```
https://thegraph.com/hosted-service/subgraph/centfinance/cent-swap-celo

**Comment by diwu1989** [comment]
Deployed the Symmetric BRegistry @ https://explorer.celo.org/address/0x3E30b138ecc85cD89210e1A19a8603544A917372/contracts

**Comment by diwu1989** [comment]
This is a pretty good GraphQL to run:
```
curl 'https://api.thegraph.com/subgraphs/name/centfinance/cent-swap-celo' \
  -H 'authority: api.thegraph.com' \
  -H 'sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="97", "Chromium";v="97"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'content-type: application/json' \
  -H 'accept: */*' \
  -H 'origin: https://thegraph.com' \
  -H 'sec-fetch-site: same-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: https://thegraph.com/' \
  -H 'accept-language: en-US,en;q=0.9' \
  --data-raw '{"query":"{\n  pools(orderBy: createTime, orderDirection: desc, where: { active: true, liquidity_gt: 0, finalized: true}) {\n    id\n    active\n    liquidity\n    tokensCount\n    tokens {\n      id\n      name\n      symbol\n      balance\n      denormWeight\n    }\n    createTime\n    swapFee\n    controller\n    publicSwap\n    finalized\n  }\n}","variables":null}' \
  --compressed
```
```
{
  pools(
    orderBy: createTime
    orderDirection: desc
    where: { active: true, liquidity_gt: 0, finalized: true }
  ) {
    id
    active
    liquidity
    tokensCount
    createTime
    swapFee
    controller
    publicSwap
    finalized
    tokens {
      id
      name
      symbol
      balance
      denormWeight
    }
  }
}

```
